--
-- PostgreSQL database dump
--

-- Dumped from database version 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
-- Dumped by pg_dump version 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: calc_game_avg_score_ondelete(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.calc_game_avg_score_ondelete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$

DECLARE average numeric; num_of_reviews int;

BEGIN
SELECT user_rating, num_of_user_reviews INTO average, num_of_reviews
FROM games
WHERE id = OLD.game_id;

UPDATE games
SET user_rating = (average * num_of_reviews - OLD.rating) / (num_of_reviews - 1)
WHERE id = OLD.game_id;

UPDATE games 
SET num_of_user_reviews = num_of_reviews - 1
WHERE id = OLD.game_id;

RETURN NULL;

END;
$$;


ALTER FUNCTION public.calc_game_avg_score_ondelete() OWNER TO postgres;

--
-- Name: calc_game_avg_score_oninsert(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.calc_game_avg_score_oninsert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE average numeric; reviews_num int;
BEGIN
SELECT user_rating, num_of_user_reviews INTO average, reviews_num 
FROM games 
WHERE id = NEW.game_id;

UPDATE games
SET user_rating = (average * reviews_num + NEW.rating)/(reviews_num + 1)
WHERE id = NEW.game_id;

UPDATE games 
SET num_of_user_reviews = reviews_num + 1
WHERE id = NEW.game_id;

RETURN NULL;

END;
$$;


ALTER FUNCTION public.calc_game_avg_score_oninsert() OWNER TO postgres;

--
-- Name: calc_game_avg_score_onupdate(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.calc_game_avg_score_onupdate() RETURNS trigger
    LANGUAGE plpgsql
    AS $$

DECLARE average numeric; average_after_delete numeric; reviews_num int;

BEGIN
SELECT user_rating, num_of_user_reviews INTO average, reviews_num
FROM games
WHERE id = NEW.game_id;

average_after_delete := (average * reviews_num - OLD.rating)/(reviews_num - 1);

UPDATE games 
SET user_rating = (average_after_delete * (reviews_num - 1) + NEW.rating) / reviews_num
WHERE id = NEW.game_id;

RETURN NULL;

END;
$$;


ALTER FUNCTION public.calc_game_avg_score_onupdate() OWNER TO postgres;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: age_restrictions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.age_restrictions (
    id integer NOT NULL,
    name text NOT NULL,
    min_age integer
);


ALTER TABLE public.age_restrictions OWNER TO postgres;

--
-- Name: age_restrictions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.age_restrictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.age_restrictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.articles (
    id integer NOT NULL,
    body text NOT NULL
);


ALTER TABLE public.articles OWNER TO postgres;

--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games (
    id integer NOT NULL,
    title text,
    release_date date,
    description text,
    publisher_id integer,
    studio_id integer,
    age_restriction_id integer,
    user_rating numeric,
    num_of_user_reviews integer,
    critic_rating numeric
);


ALTER TABLE public.games OWNER TO postgres;

--
-- Name: games_articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games_articles (
    article_id integer,
    game_id integer
);


ALTER TABLE public.games_articles OWNER TO postgres;

--
-- Name: games_genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games_genres (
    game_id integer NOT NULL,
    genre_id integer NOT NULL
);


ALTER TABLE public.games_genres OWNER TO postgres;

--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games_platforms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games_platforms (
    game_id integer NOT NULL,
    platform_id integer NOT NULL
);


ALTER TABLE public.games_platforms OWNER TO postgres;

--
-- Name: genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genres (
    id integer NOT NULL,
    name text
);


ALTER TABLE public.genres OWNER TO postgres;

--
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platforms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.platforms (
    name text NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.platforms OWNER TO postgres;

--
-- Name: platforms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platforms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publishers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.publishers (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.publishers OWNER TO postgres;

--
-- Name: publishers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.publishers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publishers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    id integer NOT NULL,
    header text,
    body text NOT NULL,
    user_id integer,
    game_id integer,
    rating integer
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: studios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.studios (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.studios OWNER TO postgres;

--
-- Name: studios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.studios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_account (
    first_name text,
    last_name text,
    phone_number text,
    email text,
    password_hash text,
    password_salt text,
    password_hash_algorithm text,
    username text NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.user_account OWNER TO postgres;

--
-- Name: user_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: age_restrictions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.age_restrictions (id, name, min_age) FROM stdin;
\.


--
-- Data for Name: articles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.articles (id, body) FROM stdin;
\.


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.games (id, title, release_date, description, publisher_id, studio_id, age_restriction_id, user_rating, num_of_user_reviews, critic_rating) FROM stdin;
2	RDR2	2020-12-12	A long time ago, in the Wild West far far away...	\N	\N	\N	7.0000000000000000	3	\N
\.


--
-- Data for Name: games_articles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.games_articles (article_id, game_id) FROM stdin;
\.


--
-- Data for Name: games_genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.games_genres (game_id, genre_id) FROM stdin;
\.


--
-- Data for Name: games_platforms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.games_platforms (game_id, platform_id) FROM stdin;
\.


--
-- Data for Name: genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.genres (id, name) FROM stdin;
\.


--
-- Data for Name: platforms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.platforms (name, id) FROM stdin;
\.


--
-- Data for Name: publishers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.publishers (id, name) FROM stdin;
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews (id, header, body, user_id, game_id, rating) FROM stdin;
1	\N	liked it very Mutch	\N	2	10
3	\N	Good	\N	2	8
4	\N	nothing special	\N	2	3
\.


--
-- Data for Name: studios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.studios (id, name) FROM stdin;
\.


--
-- Data for Name: user_account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_account (first_name, last_name, phone_number, email, password_hash, password_salt, password_hash_algorithm, username, id) FROM stdin;
\.


--
-- Name: age_restrictions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.age_restrictions_id_seq', 1, false);


--
-- Name: articles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.articles_id_seq', 1, false);


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.games_id_seq', 2, true);


--
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.genres_id_seq', 1, false);


--
-- Name: platforms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.platforms_id_seq', 1, false);


--
-- Name: publishers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.publishers_id_seq', 8, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_id_seq', 4, true);


--
-- Name: studios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.studios_id_seq', 1, false);


--
-- Name: user_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_account_id_seq', 1, false);


--
-- Name: age_restrictions age_restrictions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.age_restrictions
    ADD CONSTRAINT age_restrictions_pkey PRIMARY KEY (id);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: games_genres games_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_genres
    ADD CONSTRAINT games_genres_pkey PRIMARY KEY (game_id, genre_id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: games_platforms games_platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_platforms
    ADD CONSTRAINT games_platforms_pkey PRIMARY KEY (game_id, platform_id);


--
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- Name: platforms platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT platforms_pkey PRIMARY KEY (id);


--
-- Name: publishers publisher_name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.publishers
    ADD CONSTRAINT publisher_name_unique UNIQUE (name);


--
-- Name: publishers publishers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.publishers
    ADD CONSTRAINT publishers_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: studios studios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studios
    ADD CONSTRAINT studios_pkey PRIMARY KEY (id);


--
-- Name: user_account user_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT user_account_pkey PRIMARY KEY (id);


--
-- Name: reviews user_rating_update_ondelete; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER user_rating_update_ondelete AFTER DELETE ON public.reviews FOR EACH ROW EXECUTE PROCEDURE public.calc_game_avg_score_ondelete();


--
-- Name: reviews user_rating_update_oninsert; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER user_rating_update_oninsert AFTER INSERT ON public.reviews FOR EACH ROW EXECUTE PROCEDURE public.calc_game_avg_score_oninsert();


--
-- Name: reviews user_rating_update_onupdate; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER user_rating_update_onupdate AFTER UPDATE ON public.reviews FOR EACH ROW EXECUTE PROCEDURE public.calc_game_avg_score_onupdate();


--
-- Name: games games_age_restriction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_age_restriction_id_fkey FOREIGN KEY (age_restriction_id) REFERENCES public.age_restrictions(id) ON DELETE SET NULL;


--
-- Name: games_articles games_articles_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_articles
    ADD CONSTRAINT games_articles_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE;


--
-- Name: games_articles games_articles_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_articles
    ADD CONSTRAINT games_articles_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;


--
-- Name: games_genres games_genres_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_genres
    ADD CONSTRAINT games_genres_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;


--
-- Name: games_genres games_genres_genre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_genres
    ADD CONSTRAINT games_genres_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.genres(id) ON DELETE CASCADE;


--
-- Name: games_platforms games_platforms_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_platforms
    ADD CONSTRAINT games_platforms_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;


--
-- Name: games_platforms games_platforms_platform_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games_platforms
    ADD CONSTRAINT games_platforms_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id) ON DELETE CASCADE;


--
-- Name: games games_publisher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_publisher_id_fkey FOREIGN KEY (publisher_id) REFERENCES public.publishers(id) ON DELETE SET NULL;


--
-- Name: games games_studio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id) ON DELETE SET NULL;


--
-- Name: reviews reviews_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: reviews reviews_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_account(id);


--
-- PostgreSQL database dump complete
--

